version: "3.1"

services:
  reverse-proxy:
    build: reverse-proxy
    ports:
     - "80:80"
     - "443:443"
    secrets:
     - ssl-root-cert
     - ssl-root-key
     - ssl-root-chain
     - ssl-www-cert
     - ssl-www-key
     - ssl-www-chain
     - ssl-calendar-cert
     - ssl-calendar-key
     - ssl-calendar-chain
  www:
    build: www
  calendar:
    build: calendar
    volumes:
     - ./calendar/radicale/etc:/etc/radicale:ro
     - ${CALENDAR_VOLUME}:/var/lib/radicale

secrets:
  ssl-root-cert:
    file: reverse-proxy/ssl/root/cert.pem
  ssl-root-key:
    file: reverse-proxy/ssl/root/key.pem
  ssl-root-chain:
    file: reverse-proxy/ssl/root/chain.pem
  ssl-www-cert:
    file: reverse-proxy/ssl/www/cert.pem
  ssl-www-key:
    file: reverse-proxy/ssl/www/key.pem
  ssl-www-chain:
    file: reverse-proxy/ssl/www/chain.pem
  ssl-calendar-cert:
    file: reverse-proxy/ssl/calendar/cert.pem
  ssl-calendar-key:
    file: reverse-proxy/ssl/calendar/key.pem
  ssl-calendar-chain:
    file: reverse-proxy/ssl/calendar/chain.pem
